### ISSUE TITLE
How to rewrite any url

### ISSUE THREAD

**Issue by nierjeshkumar** [ruthgeridema/laravel-url-rewrites#15]
Hi, 
I am having following entries in web.php file:
`Route::get(
    'localities/{slug}',
    'Frontend\LocalityController@show'
)->name('locality');`

and I want  "localities/{slug}" url as "store-delivery-location/{slug}" as pretty url how I can achieve this??

**Comment by ruthgeridema** [comment]
Isn't it quicker to just do:

Route::get( 'store-delivery-location//{slug}', 'Frontend\LocalityController@show' )->name('locality');
With a 302 fallback on localities/{slug}?

**Comment by ruthgeridema** [comment]
Closed due to inactivity.
